spring:
  application:
    name: post

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://database-1.c50a0u0og3ln.ap-southeast-1.rds.amazonaws.com:3306/popup?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: cccc1111!!!!

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defalutZone: http://47.130.76.132:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 20

jwt:
  token:
    secret: 6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b
  access-token-expiration: 36000000  # 1??
  refresh-token-expiration: 604800000  # 7?
