name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: EC2에 SSH로 접속 후 서버 가동 및 Redis(Docker) 설정
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script_stop: true
          script: |
            # Docker 설치 여부 확인 및 설치
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            else
              echo "Docker is already installed."
            fi

            # 현재 사용자를 docker 그룹에 추가 (권한 문제 해결)
            sudo usermod -aG docker $USER
            newgrp docker

            # Redis 컨테이너 실행 (sudo 추가)
            if [ ! "$(sudo docker ps -q -f name=redis)" ]; then
                if [ "$(sudo docker ps -aq -f status=exited -f name=redis)" ]; then
                    # 기존 중지된 컨테이너 삭제
                    sudo docker rm redis
                fi
                # Redis 이미지 다운로드 및 컨테이너 실행
                sudo docker pull redis:latest
                sudo docker run -d --name redis --restart always -p 6379:6379 redis:latest
            else
                echo "Redis container is already running."
            fi

            # 기존 서버 정리 및 실행
            sudo rm -rf /home/ubuntu/server/auth
            sudo mkdir -p /home/ubuntu/server/auth
            sudo mv /home/ubuntu/server/auth/run.jar /home/ubuntu/server/auth/run.jar
            cd /home/ubuntu/server/auth

            # 기존 실행 중인 애플리케이션 종료
            sudo fuser -k -n tcp 8081 || true

            # 애플리케이션 실행
            nohup java -jar run.jar > ./output.log 2>&1 &